// export enum BlogReducerEnum {
//   SET_POSTS = "SET_POSTS",
// }

export enum BlogReducerEnum {
  SET_BLOG_POSTS_TMS = "SET_BLOG_POSTS_TMS",
  SET_BLOG_POSTS_WITH_COUNT_TMS = "SET_BLOG_POSTS_WITH_COUNT_TMS",
  SET_SELECTED_BLOG_USER_ID_TMS = "SET_SELECTED_BLOG_USER_ID_TMS",
  SET_COMMENTS_MODAL_STATUS_TMS = "SET_COMMENTS_MODAL_STATUS_TMS",
  SET_IS_LOADING_STATUS_TMS = "SET_IS_LOADING_STATUS_TMS",
  SET_SEARCH_STRING_TMS = "SET_SEARCH_STRING_TMS",
  SET_COMMENTS_TMS = "SET_COMMENTS_TMS",
  SET_ACTIVE_POST_TMS = "SET_ACTIVE_POST_TMS",
  SET_CURRENT_PAGE = "SET_CURRENT_PAGE",
  SET_COUNT_OF_POSTS = "SET_COUNT_OF_PAGES"
}
